# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXUhwuwaDhcq332BooabILsFK4sDXGix
"""

# 2 Faça um programa que verifique e mostre os números entre 1.000 e 2.000 (inclusive) que, quando divididos por 11 produzam resto igual a 2
for i in range(1000, 2001):
 if i % 11 == 2:
  print(i)

# 3 Faça um programa que leia 5 números e informe a soma e a média dosnúmeros.
soma = 0
for i in range(5):
  numero = float(input(f"digite o {i+1}º numero: "))
  soma += numero
  media =soma/5
print(f"a soma dos numeros e igual {soma} e a media {media} ")

# 4 Faça um programa que receba um número e usando laços de repetição calcule e mostre a tabuada desse número.
numero = int(input("e digite um numero para caucular a tabuada"))
print(f"taboada do {numero}")
for i in range(1, 11):
  resultado = numero *i
  print(resultado)

# 5 Faça um programa que mostre as tabuadas dos números de 1 a 10 usando laços de repetição.
for n1 in range(1, 11):
  for n2 in range(1, 11):
    print(f"{n1} x {n2}={n1*n2}")

# 6 Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.
for i in range(1, 21):
  print(i)
for i in range(1, 21):
  print(i, end = '')

# 7 Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.
for i in range(1, 51):
  if i % 2 != 0:
    print(i)

# 8 Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.
numero1 = int(input("digite o primeiro numero inteiro"))
numero2 = int(input("digite o segundo numero inteiro"))
for i in range(numero1, numero2):
  print(i)

# 9 Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor mostre na tela uma mensagem contendo em quanto foi superado o fatura
lojaB = 54000
lojaA = 0
for i in range(5):
  valor = float(input("digite um valor"))
  lojaA += valor
if lojaA > lojaB:
  print("o faturamento da loja A é maior que loja B")
elif lojaB > lojaA:
  print("o faturamento da Loja Bé maior que Loja A")
else:
  print("o valor do faturamento de ambas é igual")

# 10 Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares.
impar= 0
par= 0
for i in range(10):
   numero = int(input(f"digite o {i+1} numero inteiro"))
   if numero % 2 == 0:
    par +=
   else:
     impar +=1
print(f"numero impares = {impar} e numero pares = {par}")

# 11 Um funcionário de uma empresa recebe aumento salarial anualmente: Sabe-se que:
salario = float(input("Digite o salario inicial do funcionario: "))
percentual = 0.015
for i in range(1996, 2025):
 aumento = salario * percentual
 salario += aumento
 percentual *= 2

 print(f"salario em {i} = {salario:.2f}")

#12
for i in range(9999):
 nota = int(input("digite uma nota de 0 a 10)"))
if nota > 0 and nota < 10:
 print("nota valida")
else:
 print("nota invalida, digite uma nota de 0 a 10")

#13
valor = float(input('digite o valor da compra: '))
contagem = 1
if valor >= 600 and contagem:
 redezido = valor - 500
 if reduzido >= 100 or contagem <= 24:
  for x in range(999):
    contagem += 1
    reduzido -= 100
  if reduzido < 100 or contagem == 24:
    break

 porcentagem = contagem/100
 desconto = valor * porcentagem
 final = valor - desconto
 print(f"o produto de R${valor:.2f}ficara a partir de R${final} com {contagem:.0f}% de desconto")

"""Faça um programa que verifique e mostre os números entre 1.000 e 2.00(inclusive) que, quando divididos por 10 produzam resto igual a 5 em todos"""

for i in range(5000, 10001):
  if i % 10 == 5:
   print(i)

"""faça um programa que peça um numero para a taboada e coloque um limite de contas que ela deve fazer"""

numero = int(input("digite um numero da taboada"))
limite = int(input("Digite o limite para a tabuada: "))
print(f"Tabuada do {numero} até o limite {limite}:")
for i in range(1, limite + 1):
    print(f"{numero} x {i} = {numero * i}")

a = homem
b = homem
c = mulher

if homem > homem:
  print(homem)
  elif
  print()

"""verifique se o numero e negativo ou positivo e mostre"""

numero = float(input("Digite um número: "))
 if numero > 0:
    print("O número é positivo.")
 elif numero < 0:
    print("O número é negativo.")
 else:
    print("O número é zero.")

"""crie um programa que baseado na sua idade indentifique se a pessoa e criança jovem, adulto ou idoso"""

idade = int(input("Digite sua idade: "))
 if idade < 1:
    print("Idade inválida. Por favor, insira uma idade válida seu paspalho.")
 elif idade < 13:
    print("Você é uma criança.")
 elif idade < 20:
    print("Você é um adolescente.")
 elif idade < 65:
    print("Você é um adulto.")
 else:
    print("Você é um idoso.")